# Generated by Django 3.0.2 on 2020-02-11 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenceChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('preference', models.PositiveSmallIntegerField(choices=[(1, 'ATE'), (2, 'NOT_ATE')], default=1, verbose_name='食べた or 食べていないflag')),
                ('choice_status', models.IntegerField(blank=True, choices=[(6, 'ATE_THREE'), (5, 'ATE_TWO'), (4, 'ATE_ONE'), (3, 'ATE_ZERO'), (2, 'NOT_ATE_TWO'), (1, 'NOT_ATE_ONE'), (0, 'NOT_ATE_ZERO')], null=True, verbose_name='感想の選択肢')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('text', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='投票の感想.')),
                ('choices', models.ManyToManyField(to='polls.PreferenceChoice', verbose_name='好みの選択肢')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='商品')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投票ユーザーyu-za-')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
